apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: example-cluster
spec:
  forProvider:
    location: us-east1
    initialClusterVersion: latest

---

apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: example-cluster
spec:
  forProvider:
    locations:
    - us-east1-b
    clusterRef:
      name: example-cluster
    config:
      preemptible: true
      machineType: e2-standard-2
      oauthScopes:
      - "https://www.googleapis.com/auth/devstorage.read_only"
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/servicecontrol"
      - "https://www.googleapis.com/auth/service.management.readonly"
      - "https://www.googleapis.com/auth/trace.append"      
    initialNodeCount: 3
    management:
      autoUpgrade: false
